name: Fuzz scanner

on:
  push:
    branches: ["*"]
    paths:
      - src/scanner.c
  pull_request:
    branches: ["*"]
    paths:
      - src/scanner.c

jobs:
  test:
    uses: tree-sitter-grammars/.github/.github/workflows/fuzz.yml@main
    with:
        language: svelte
